backend/controllers/OrderController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Order;
use common\models\OrderSearch;
use yii\data\ArrayDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'new', 'done', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        // Unserialize products in the cart
        $data = unserialize($model->data);
        $dataProvider = new ArrayDataProvider([
            'allModels' => $data,
        ]);

        // Change status
        if ($model->status === 1) {
            $model->status = 2;
            $model->save();
        }

        return $this->render('view', [
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Deletes an existing Order model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Sets status to 1
     * If action is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionNew($id)
    {
        $model = $this->findModel($id);
        $model->status = 1;
        $model->save();

        return $this->redirect(['index']);
    }

    /**
     * Sets status to 3
     * If action is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDone($id)
    {
        $model = $this->findModel($id);
        $model->status = 3;
        $model->save();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use common\models\Category;
use common\models\Order;
use common\models\Product;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use backend\models\LoginForm;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Order::find()->limit(10)->where(['status' => Order::STATUS_NEW]),
        ]);

        $productModel = new Product(['scenario' => 'create']);
        $productModel->date = date('Y-m-d H:i');

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'categoryModel' => new Category(),
            'productModel' => $productModel,
        ]);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Product;
use Yii;
use yii\data\ArrayDataProvider;
use yii\web\Controller;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        $this->layout = 'fullwide';
        $dataProvider = new ArrayDataProvider([
            'allModels' => Product::find()->limit(8)->orderBy('date DESC')->all()
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }
}

backend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

</div>

backend/views/site/index.php
<?php

use common\models\Order;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $categoryModel common\models\Category */
/* @var $productModel common\models\Product */

$this->title = Yii::t('yii', 'Home');
?>

<h1 class="page-header">
    <?= Yii::t('backend/site', 'New Orders') ?>
    <?= Html::a(
        Yii::t('backend/site', 'All Orders'),
        ['order/index'],
        ['class' => 'btn btn-primary pull-right']
    ) ?>
</h1>

<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'summaryOptions' => ['class' => 'alert alert-info'],
    'rowOptions' => function ($model) {
        /** @var $model common\models\Order */
        if ($model->status === Order::STATUS_NEW) {
            return ['class' => 'success'];
        } elseif ($model->status === Order::STATUS_REVIEWED) {
            return ['class' => 'info'];
        }

        return ['class' => 'active'];
    },
    'columns' => [
        'id',
        'name',
        'total_cost:currency',
        'date:datetime',
        [
            'attribute' => 'status',
            'value' => function ($model) {
                /** @var $model common\models\Order */
                return $model->getStatusLabel($model->status);
            }
        ],
        // 'email:email',
        // 'phone',
        // 'message:ntext',

        [
            'class' => 'common\components\ActionButtonGroupColumn',
            'template' => '{view}',
            'buttons' => [
                'view' => function ($url, $model, $key) {
                    return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['order/view', 'id' => $model->id], [
                        'class' => 'btn btn-xs btn-primary'
                    ]);
                },
            ],
        ],
    ],
]) ?>

<h1 class="page-header">
    <?= Yii::t('backend/site', 'Short Actions') ?>
</h1>

<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseCategory" aria-expanded="true" aria-controls="collapseOne">
                <?= Yii::t('backend/site', 'Create Category') ?>
            </a>
        </h4>
    </div>
    <div id="collapseCategory" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
            <?= $this->render('/category/_form', [
                'model' => $categoryModel,
            ]) ?>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                <?= Yii::t('backend/site', 'Create Product') ?>
            </a>
        </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
            <?= $this->render('/product/_form', [
                'model' => $productModel,
            ]) ?>
        </div>
    </div>
</div>

backend/views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model backend\models\LoginForm */

$this->title = Yii::t('backend/login', 'Login');
$this->params['breadcrumbs'][] = $this->title;
?>

<h1 class="page-header"><?= $this->title ?></h1>

<div class="row">
    <div class="col-lg-5">
        <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
            <?= $form->field($model, 'username') ?>
            <?= $form->field($model, 'password')->passwordInput() ?>
            <?= $form->field($model, 'rememberMe')->checkbox() ?>
            <div class="form-group">
                <?= Html::submitButton(
                    Yii::t('backend/login', 'Login'),
                    ['class' => 'btn btn-primary', 'name' => 'login-button']
                ) ?>
            </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>