frontend/controllers/CartController.php
<?php

namespace frontend\controllers;

use common\models\Product;
use common\models\Order;
use Yii;
use yii\data\ArrayDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class CartController extends Controller
{
    public function actionIndex()
    {
        $dataProvider = new ArrayDataProvider([
            'allModels' => Yii::$app->cart->getPositions(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionAdd($id)
    {
        $model = $this->findModel($id);

        Yii::$app->cart->put($model, 1);

        return $this->redirect(['index']);
    }

    public function actionRemove($id)
    {
        $model = $this->findModel($id);

        Yii::$app->cart->remove($model);

        return $this->redirect(['index']);
    }

    public function actionClear()
    {
        Yii::$app->cart->removeAll();

        return $this->redirect(['index']);
    }

    public function actionOrder()
    {
        $cartPositions = Yii::$app->cart->getPositions();

        if (!$cartPositions or $cartPositions === null) {
            return $this->redirect(['index']);
        }

        $dataProvider = new ArrayDataProvider([
            'allModels' => $cartPositions,
        ]);

        $model = new Order();

        if ($model->load(Yii::$app->request->post())) {
            $model->status = 1;
            $model->total_cost = Yii::$app->cart->getCost();
            $model->date = date('Y-m-d H:i');
            $model->data = Yii::$app->cart->getSerialized();

            if ($model->validate() && $model->save()) {
                Yii::$app->cart->removeAll();

                return $this->render('orderSuccess', [
                    'model' => $model,
                ]);
            }
        }

        return $this->render('order', [
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Finds the Product model based on its slug.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Product the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('frontend', 'The requested page does not exist.'));
        }
    }

}

frontend/controllers/CatalogController.php
<?php

namespace frontend\controllers;

use common\models\Category;
use Yii;
use common\models\Product;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class CatalogController extends Controller
{
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Product::find(),
            'sort' => [
                'defaultOrder' => [
                    'date' => SORT_DESC,
                ]
            ],
            'pagination' => [
                'forcePageParam' => false,
                'pageSizeParam' => false,
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($slug)
    {
        $model = $this->findModel($slug);

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionCategory($category)
    {
        $model = $this->findCategory($category);

        $dataProvider = new ActiveDataProvider([
            'query' => $model->getProducts(),
            'sort' => [
                // Order by date for default
                'defaultOrder' => [
                    'date' => SORT_DESC,
                ]
            ],
            'pagination' => [
                // Prevent creating additional params in the URL. For SEO
                'forcePageParam' => false,
                'pageSizeParam' => false,
            ],
        ]);

        return $this->render('category', [
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Finds the Product model based on its slug.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $slug
     * @return Product the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($slug)
    {
        if (($model = Product::findOne(['slug' => $slug])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('frontend', 'The requested page does not exist.'));
        }
    }

    /**
     * Finds the Category model based on its slug.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $slug
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findCategory($slug)
    {
        if (($model = Category::findOne(['slug' => $slug])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('frontend', 'The requested page does not exist.'));
        }
    }

}

frontend/views/catalog/_nav.php
<?php
use common\models\Category;
use yii\bootstrap\Nav;

/* @var $this yii\web\View */

// Items
$navItems = [];
foreach (Category::find()->all() as $category) {
    $label = $category->name
        . '<span class="badge pull-right">'
        . $category->getProducts()->count()
        . '</span>';

    $navItems[] = [
        'label' => $label,
        'url' => ['catalog/category', 'category' => $category->slug],
    ];
}

echo Nav::widget([
    'items' => $navItems,
    'options' => ['class' => 'nav-pills nav-stacked'],
    'encodeLabels' => false,
]);

frontend/views/catalog/_product.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Product */
/* @var $class */
?>
<div class="<?= $class ?>">
    <div class="panel panel-default panel-product">
        <div class="panel-image">
            <?= Html::img($model->mainImage, [
                'class' => 'img-responsive',
            ]) ?>

            <?php if ($model->status_id): ?>
                <div class="promotion">
                    <span class="status"
                          style="color: <?= $model->status->color ?>;
                              background: <?= $model->status->background ?>">
                        <?= $model->status->name ?>
                    </span>
                </div>
            <?php endif ?>
        </div>
        <div class="panel-body">
            <h4>
                <?= Html::encode($model->name) ?>
            </h4>

            <p class="text-muted">
                <?= Html::a($model->category->name, ['catalog/category', 'category' => $model->category->slug], [
                    'class' => 'category-link',
                ]) ?>
            </p>

            <p><?= Yii::$app->formatter->asCurrency($model->price) ?></p>

            <?= Html::a(Yii::t('frontend/catalog', 'View'), ['catalog/view', 'slug' => $model->slug, 'category' => $model->category->slug], [
                'class' => 'btn btn-primary',
            ]) ?>
        </div>
    </div>
</div>

frontend/views/catalog/category.php
<?php
use yii\helpers\Html;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $model common\models\Category */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = $model->name;

$this->params['breadcrumbs'][] = ['label' => Yii::t('frontend/catalog', 'Catalog'), 'url' => ['catalog/index']];

if ($model->parent) {
    $this->title .= ' - ' . $model->parent->name;

    $this->params['breadcrumbs'][] = [
        'label' => $model->parent->name,
        'url' => ['catalog/category', 'category' => $model->parent->slug]
    ];
}

$this->params['breadcrumbs'][] = $model->name;

$this->registerMetaTag(['name' => 'description', 'content' => $model->meta_description]);
$this->registerMetaTag(['name' => 'keywords', 'content' => $model->meta_keywords]);
?>
<div class="row">
    <div class="col-lg-3 col-md-3 col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?= Yii::t('frontend/catalog', 'Categories') ?>
            </div>

            <div class="panel-body">
                <?= $this->render('_nav') ?>
            </div>
        </div>
    </div>
    <div class="col-lg-9 col-md-9 col-sm-12">
        <h1><?= Html::encode($this->title) ?></h1>

        <blockquote>
            <?= $model->description ?>
        </blockquote>

        <div class="child-categories">
            <?php foreach ($model->categories as $category): ?>
                <?= Html::a($category->name, ['catalog/category', 'category' => $category->slug], [
                    'class' => 'btn btn-lg btn-primary col-sm-4',
                ]) ?>
            <?php endforeach ?>
            <div class="clearfix"></div>
        </div>

        <div class="well">
            <?= Yii::t('frontend/catalog', 'Order by:') ?>

            <?= $dataProvider->sort->link('name', [
                'class' => 'btn btn-primary btn-sm'
            ]) ?>
            <?= $dataProvider->sort->link('price', [
                'class' => 'btn btn-primary btn-sm'
            ]) ?>
            <?= $dataProvider->sort->link('date', [
                'class' => 'btn btn-primary btn-sm'
            ]) ?>
        </div>

        <?= ListView::widget([
            'layout' => "{summary}\n<div class=\"row\">{items}</div>\n{pager}",
            'dataProvider' => $dataProvider,
            'itemView' => '_product',
            'viewParams' => ['class' => 'col-sm-4 col-lg-4 col-md-4 col-xs-6'],
            'summaryOptions' => [
                'class' => 'alert alert-info'
            ],
        ]) ?>
    </div>
</div>

frontend/views/catalog/index.php
<?php
use yii\helpers\Html;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('frontend/catalog', 'Catalog');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-lg-3 col-md-3 col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?= Yii::t('frontend/catalog', 'Categories') ?>
            </div>

            <div class="panel-body">
                <?= $this->render('_nav') ?>
            </div>
        </div>
    </div>
    <div class="col-lg-9 col-md-9 col-sm-12">
        <h1><?= Html::encode($this->title) ?></h1>

        <div class="well">
            <?= Yii::t('frontend/catalog', 'Order by:') ?>
            <?= $dataProvider->sort->link('name', [
                'class' => 'btn btn-primary btn-sm'
            ]) ?>
            <?= $dataProvider->sort->link('category_id', [
                'class' => 'btn btn-primary btn-sm'
            ]) ?>
            <?= $dataProvider->sort->link('price', [
                'class' => 'btn btn-primary btn-sm'
            ]) ?>
            <?= $dataProvider->sort->link('date', [
                'class' => 'btn btn-primary btn-sm'
            ]) ?>
        </div>

        <?= ListView::widget([
            'layout' => "{summary}\n<div class=\"row\">{items}</div>\n{pager}",
            'dataProvider' => $dataProvider,
            'itemView' => '_product',
            'viewParams' => ['class' => 'col-sm-4 col-lg-4 col-md-4 col-xs-6'],
            'summaryOptions' => [
                'class' => 'alert alert-info'
            ],
        ]) ?>
    </div>
</div>

frontend/views/catalog/shareLinks.php
<?php
use ijackua\sharelinks\ShareLinks;
use yii\helpers\Html;
use kartik\icons\Icon;

/* @var $this yii\web\View */

// FontAwesome icons
Icon::map($this, Icon::FA);
?>

<div class="socialShareBlock">
    <?= Html::a(Icon::show('facebook'),
        $this->context->shareUrl(ShareLinks::SOCIAL_FACEBOOK),
        [
            'title' => Yii::t('frontend/catalog', 'Share on Facebook'),
            'class' => 'btn btn-xs btn-default',
        ]
    ) ?>
    <?= Html::a(Icon::show('twitter'),
        $this->context->shareUrl(ShareLinks::SOCIAL_TWITTER),
        [
            'title' => Yii::t('frontend/catalog', 'Share on Twitter'),
            'class' => 'btn btn-xs btn-default',
        ]
    ) ?>
    <?= Html::a(Icon::show('google-plus'),
        $this->context->shareUrl(ShareLinks::SOCIAL_GPLUS),
        [
            'title' => Yii::t('frontend/catalog', 'Share on Google Plus'),
            'class' => 'btn btn-xs btn-default',
        ]
    ) ?>
    <?= Html::a(Icon::show('vk'),
        $this->context->shareUrl(ShareLinks::SOCIAL_VKONTAKTE),
        [
            'title' => Yii::t('frontend/catalog', 'Share on VK'),
            'class' => 'btn btn-xs btn-default',
        ]
    ) ?>
</div>

frontend/views/catalog/view.php
<?php
use common\models\Image;
use dosamigos\gallery\Gallery;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Product */

$this->title = $model->name . ' - ' . $model->category->name;

$this->params['breadcrumbs'][] = ['label' => Yii::t('frontend/catalog', 'Catalog'), 'url' => ['catalog/index']];

if ($model->category->parent) {
    $this->title .= ' - ' . $model->category->parent->name;
    $this->params['breadcrumbs'][] = ['label' => $model->category->parent->name, 'url' => ['catalog/category', 'category' => $model->category->parent->slug]];
}

$this->params['breadcrumbs'][] = ['label' => $model->category->name, 'url' => ['catalog/category', 'category' => $model->category->slug]];
$this->params['breadcrumbs'][] = $model->name;

// Meta tags
$this->registerMetaTag(['name' => 'description', 'content' => $model->meta_description]);
$this->registerMetaTag(['name' => 'keywords', 'content' => $model->meta_keywords]);

// Gallery images
$galleryItems[] = [
    'src' => Yii::$app->urlManager->baseUrl . '/uploads/product/' . $model->id . '/main.jpg',
    'options' => [
        'title' => $model->name,
    ],
];
foreach (Image::findAll(['model_id' => $model->id]) as $image) {
    $galleryItems[] = [
        'src' => Yii::$app->urlManager->baseUrl . '/uploads/product/' . $model->id . '/' . $image->id . '.jpg',
        'options' => [
            'title' => $model->name,
        ],
    ];
}
?>

<div class="row">
    <div class="col-sm-6">
        <?= Gallery::widget([
            'items' => $galleryItems,
            'id' => 'product-gallery-links',
        ]) ?>
    </div>

    <div class="col-sm-6">
        <h1 class="product-header">
            <?= $model->name ?>
        </h1>

        <hr>

        <p class="product-description">
            <?= $model->description ?>
        </p>

        <hr>

        <div class="product-price">
            <?= Yii::$app->formatter->asCurrency($model->price) ?>
            <?php if ($model->status_id): ?>
                <span class="status"
                      style="color: <?= $model->status->color ?>;
                          background: <?= $model->status->background ?>;
                          font-size: inherit">
                    <?= $model->status->name ?>
                </span>
            <?php endif ?>
        </div>

        <hr>

        <div class="product-button">
            <?= Html::a(Yii::t('frontend/catalog', 'Add To Cart'), ['cart/add', 'id' => $model->id], [
                'class' => 'btn btn-primary btn-lg'
            ]) ?>
        </div>

        <hr>

        <div class="row">
            <div class="col-sm-4">
                <h4><?= Yii::t('frontend/catalog', 'Share') ?></h4>
                <?= ijackua\sharelinks\ShareLinks::widget([
                    'viewName' => '@frontend/views/catalog/shareLinks',
                ]) ?>
            </div>
            <div class="col-sm-4">
                <h4><?= Yii::t('frontend/catalog', 'Category') ?></h4>
                <?= Html::a($model->category->name, ['catalog/category', 'category' => $model->category->slug]) ?>
            </div>
            <div class="col-sm-4">
                <h4><?= Yii::t('frontend/catalog', 'Date Created') ?></h4>
                <?= Yii::$app->formatter->asDatetime($model->date) ?>
            </div>
        </div>
    </div>
</div>