common/models/Order.php
<?php

namespace common\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%order}}".
 *
 * @property integer $id
 * @property integer $status
 * @property integer $total_cost
 * @property string $date
 * @property string $data
 * @property string $name
 * @property string $email
 * @property string $phone
 * @property string $message
 */
class Order extends ActiveRecord
{
    const STATUS_NEW = 1;
    const STATUS_REVIEWED = 2;
    const STATUS_PROCESSED = 3;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%order}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status', 'total_cost', 'date', 'data', 'name', 'phone'], 'required'],
            [['status', 'total_cost'], 'integer'],
            [['date'], 'safe'],
            [['data', 'message'], 'string'],
            [['name', 'email', 'phone'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('common/order', 'ID'),
            'status' => Yii::t('common/order', 'Status'),
            'total_cost' => Yii::t('common/order', 'Total Cost'),
            'date' => Yii::t('common/order', 'Date'),
            'data' => Yii::t('common/order', 'Data'),
            'name' => Yii::t('common/order', 'Name'),
            'email' => Yii::t('common/order', 'Email'),
            'phone' => Yii::t('common/order', 'Phone'),
            'message' => Yii::t('common/order', 'Message'),
        ];
    }

    public function getStatuses()
    {
        return [
            self::STATUS_NEW => Yii::t('common/order', 'New'),
            self::STATUS_REVIEWED => Yii::t('common/order', 'Reviewed'),
            self::STATUS_PROCESSED => Yii::t('common/order', 'Processed'),
        ];
    }

    public function getStatusLabel($status)
    {
        return $this->statuses[$status];
    }
}

backend/controllers/OrderController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Order;
use common\models\OrderSearch;
use yii\data\ArrayDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'new', 'done', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        // Unserialize products in the cart
        $data = unserialize($model->data);
        $dataProvider = new ArrayDataProvider([
            'allModels' => $data,
        ]);

        // Change status
        if ($model->status === 1) {
            $model->status = 2;
            $model->save();
        }

        return $this->render('view', [
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Deletes an existing Order model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Sets status to 1
     * If action is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionNew($id)
    {
        $model = $this->findModel($id);
        $model->status = 1;
        $model->save();

        return $this->redirect(['index']);
    }

    /**
     * Sets status to 3
     * If action is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDone($id)
    {
        $model = $this->findModel($id);
        $model->status = 3;
        $model->save();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/ProductController.php
<?php

namespace backend\controllers;

use common\models\Image;
use Yii;
use common\models\Product;
use common\models\ProductSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update' , 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Product model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Product model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Product(['scenario' => 'create']);
        $model->date = date('Y-m-d H:i');

        if ($model->load(Yii::$app->request->post())) {
            $model->image = UploadedFile::getInstance($model, 'image');
            $model->images = UploadedFile::getInstances($model, 'images');

            if ($model->validate() && $model->save() && $model->image) {
                // Working directory
                $dir = Yii::getAlias('@frontend/web/uploads/product/' . $model->id);
                FileHelper::createDirectory($dir);

                // Save main image
                $model->image->saveAs($dir . '/main.jpg');

                // Save images
                if ($model->images) {
                    foreach ($model->images as $image) {
                        $imageModel = new Image();
                        $imageModel->model_id = $model->id;
                        $imageModel->save();

                        $image->saveAs($dir . '/' . $imageModel->id . '.jpg');
                    }
                }
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Product model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->image = UploadedFile::getInstance($model, 'image');
            $model->images = UploadedFile::getInstances($model, 'images');

            if ($model->validate() && $model->save()) {
                $dir = Yii::getAlias('@frontend/web/uploads/product/' . $model->id);

                if ($model->image) {
                    $model->image->saveAs($dir . '/main.jpg');
                }

                if ($model->images) {
                    $imageModels = Image::findAll(['model_id' => $model->id]);
                    if ($imageModels) {
                        foreach ($imageModels as $image) {
                            $file = $dir . '/' . $image->id . '.jpg';

                            if (file_exists($file)) {
                                unlink($file);
                            }

                            $image->delete();
                        }
                    }

                    foreach ($model->images as $image) {
                        $imageModel = new Image();
                        $imageModel->model_id = $model->id;
                        $imageModel->save();

                        $image->saveAs($dir . '/' . $imageModel->id . '.jpg');
                    }
                }
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Product model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        $dir = Yii::getAlias('@frontend/web/uploads/product/' . $model->id);

        FileHelper::removeDirectory($dir);

        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Product model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Product the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/order/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\OrderSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                <?= Yii::t('backend/order', 'Search Orders') ?>
            </a>
        </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
            <div class="order-search">

                <?php $form = ActiveForm::begin([
                    'action' => ['index'],
                    'method' => 'get',
                ]); ?>

                <?= $form->field($model, 'id') ?>

                <?= $form->field($model, 'status')->dropDownList($model->getStatuses(), [
                    'prompt' => Yii::t('backend/order', '- select status -'),
                ]) ?>

                <?= $form->field($model, 'total_cost') ?>

                <?= $form->field($model, 'name') ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'phone') ?>

                <?= $form->field($model, 'date') ?>

                <?php // echo  $form->field($model, 'data') ?>

                <?php // echo $form->field($model, 'message') ?>

                <div class="form-group">
                    <?= Html::submitButton(Yii::t('backend/order', 'Search'), ['class' => 'btn btn-primary']) ?>
                    <?= Html::resetButton(Yii::t('backend/order', 'Reset'), ['class' => 'btn btn-default']) ?>
                </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>
</div>

backend/views/order/index.php
<?php

use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\OrderSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('backend/order', 'Orders');

$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-index">

    <h1 class="page-header">
        <?= $this->title ?>
    </h1>

    <?= $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'summaryOptions' => ['class' => 'alert alert-info'],
        'rowOptions' => function ($model) {
            /** @var $model common\models\Order */
            if ($model->status === 1) {
                return ['class' => 'success'];
            } elseif ($model->status === 2) {
                return ['class' => 'info'];
            }

            return ['class' => 'active'];
        },
        'columns' => [
            'id',
            'name',
            'total_cost:currency',
            'date:datetime',
            [
                'attribute' => 'status',
                'value' => function ($model) {
                    /** @var $model common\models\Order */
                    return $model->getStatusLabel($model->status);
                }
            ],
            // 'email:email',
            // 'phone',
            // 'message:ntext',

            [
                'class' => 'common\components\ActionButtonGroupColumn',
                'template' => '{view} {delete}',
            ],
        ],
    ]); ?>

</div>

backend/views/order/view.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Order */
/* @var $dataProvider yii\data\ArrayDataProvider */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend/order', 'Orders'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-view">

    <h1 class="page-header">
        <?= Yii::t('backend/order', 'Order #{orderID}', [
            'orderID' => $model->id,
        ]) ?>

        <div class="btn-group pull-right">
            <?= Html::a(Yii::t('backend/order', 'New'), ['new', 'id' => $model->id], [
                'class' => 'btn btn-default',
                'data-toggle' => 'tooltip',
                'title' => Yii::t('backend/order', 'Set this order as new'),
            ]) ?>
            <?= Html::a(Yii::t('backend/order', 'Done'), ['done', 'id' => $model->id], [
                'class' => 'btn btn-success',
                'data-toggle' => 'tooltip',
                'title' => Yii::t('backend/order', 'Set this order as done'),
            ]) ?>
            <?= Html::a(Yii::t('backend/order', 'Delete'), ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ]) ?>
        </div>
    </h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'status',
                'value' => $model->getStatusLabel($model->status),
            ],
            'total_cost:currency',
            'date:datetime',
            'name',
            'email:email',
            'phone',
            'message:ntext',
        ],
    ]) ?>

    <h2><?= Yii::t('backend/order', 'Products') ?></h2>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'layout' => '{items}',
        'columns' => [
            [
                'attribute' => 'image',
                'format' => 'raw',
                'value' => function ($model) {
                    /** @var $model common\models\Product */
                    return Html::img($model->getMainImage('urlManagerFrontEnd'), [
                        'width' => 80,
                    ]);
                },
                'contentOptions' => [
                    'style' => 'width: 15%',
                ],
            ],
            [
                'attribute' => 'name',
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::a($model->name, ['product/view', 'id' => $model->id]);
                },
            ],
            'price:currency',
        ],
    ]) ?>

</div>